import type { 
  Trip, 
  ItineraryDay, 
  ChatMessage, 
  Expert, 
  Card, 
  MilesProgram, 
  RouteTemplate, 
  Flight, 
  Hotel, 
  Experience,
  Plan
} from './types';

export const currentTrip: Trip = {
  id: '1',
  title: 'Toscana Romântica',
  destination: 'Toscana, Itália',
  startDate: '2025-06-15',
  endDate: '2025-06-22',
  status: 'planning',
  coverImage: 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800',
  totalDays: 7,
  travelers: 2,
  budget: 'R$ 25.000',
};

export const myTrips: Trip[] = [
  currentTrip,
  {
    id: '2',
    title: 'Disney Mágica',
    destination: 'Orlando, EUA',
    startDate: '2025-03-10',
    endDate: '2025-03-17',
    status: 'confirmed',
    coverImage: 'https://images.unsplash.com/photo-1597466599360-3b9775841aec?w=800',
    totalDays: 7,
    travelers: 4,
    budget: 'R$ 45.000',
  },
  {
    id: '3',
    title: 'Maldivas Paradisíaca',
    destination: 'Ilhas Maldivas',
    startDate: '2024-12-20',
    endDate: '2024-12-27',
    status: 'completed',
    coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    totalDays: 7,
    travelers: 2,
    budget: 'R$ 35.000',
  },
];

export const itineraryDays: ItineraryDay[] = [
  {
    id: 'd1',
    dayNumber: 1,
    date: '2025-06-15',
    title: 'Chegada em Florença',
    intensity: 'low',
    activities: [
      {
        id: 'a1',
        time: '10:30',
        period: 'morning',
        title: 'Chegada no Aeroporto de Florença',
        description: 'Desembarque e traslado privativo até o hotel.',
        location: 'Aeroporto Amerigo Vespucci',
        duration: '1h30',
        type: 'transport',
        tips: ['Guarde os recibos para reembolso do transfer'],
        benefits: ['Transfer incluso no pacote premium'],
      },
      {
        id: 'a2',
        time: '12:30',
        period: 'afternoon',
        title: 'Check-in Hotel & Degustação',
        description: 'Check-in no Four Seasons Firenze com welcome drink.',
        location: 'Four Seasons Hotel Firenze',
        duration: '1h',
        type: 'accommodation',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
        benefits: ['Late checkout garantido', 'Upgrade de quarto'],
        miles: 5000,
      },
      {
        id: 'a3',
        time: '14:00',
        period: 'afternoon',
        title: 'Almoço no Giardino di Boboli',
        description: 'Experiência gastronômica com vista para os jardins.',
        location: 'Giardino di Boboli',
        duration: '2h',
        type: 'food',
        price: 'R$ 450',
        tips: ['Peça o menu degustação', 'Reserva antecipada recomendada'],
      },
      {
        id: 'a4',
        time: '17:00',
        period: 'evening',
        title: 'Passeio pela Ponte Vecchio',
        description: 'Caminhada romântica pela ponte mais famosa de Florença.',
        location: 'Ponte Vecchio',
        duration: '1h30',
        type: 'experience',
        image: 'https://images.unsplash.com/photo-1541370976299-4d24ebbc9077?w=400',
      },
      {
        id: 'a5',
        time: '20:00',
        period: 'evening',
        title: 'Jantar no Enoteca Pinchiorri',
        description: 'Jantar com estrela Michelin em ambiente íntimo.',
        location: 'Enoteca Pinchiorri',
        duration: '3h',
        type: 'food',
        price: 'R$ 1.200',
        tips: ['Dress code: smart casual', 'Harmonização de vinhos recomendada'],
      },
    ],
  },
  {
    id: 'd2',
    dayNumber: 2,
    date: '2025-06-16',
    title: 'Arte e Cultura em Florença',
    intensity: 'medium',
    activities: [
      {
        id: 'a6',
        time: '08:00',
        period: 'morning',
        title: 'Café da manhã no hotel',
        description: 'Buffet completo com produtos locais frescos.',
        location: 'Four Seasons Hotel Firenze',
        duration: '1h',
        type: 'food',
      },
      {
        id: 'a7',
        time: '09:30',
        period: 'morning',
        title: 'Galleria degli Uffizi',
        description: 'Visita guiada privativa com historiador de arte.',
        location: 'Galleria degli Uffizi',
        duration: '3h',
        type: 'attraction',
        image: 'https://images.unsplash.com/photo-1504730030853-eff311f57d3c?w=400',
        price: 'R$ 280',
        tips: ['Chegue cedo para evitar filas', 'Não perca o Nascimento de Vênus'],
        benefits: ['Entrada prioritária inclusa'],
      },
      {
        id: 'a8',
        time: '13:00',
        period: 'afternoon',
        title: 'Almoço no Mercato Centrale',
        description: 'Experiência gastronômica no coração de Florença.',
        location: 'Mercato Centrale',
        duration: '1h30',
        type: 'food',
        price: 'R$ 150',
      },
      {
        id: 'a9',
        time: '15:00',
        period: 'afternoon',
        title: 'Duomo de Florença',
        description: 'Subida à cúpula de Brunelleschi com vista panorâmica.',
        location: 'Cattedrale di Santa Maria del Fiore',
        duration: '2h',
        type: 'attraction',
        image: 'https://images.unsplash.com/photo-1534359265607-b9dad788a876?w=400',
        price: 'R$ 120',
        tips: ['São 463 degraus - use sapatos confortáveis'],
      },
      {
        id: 'a10',
        time: '18:00',
        period: 'evening',
        title: 'Tempo livre para compras',
        description: 'Explore as lojas de couro e joias artesanais.',
        location: 'Centro Histórico',
        duration: '2h',
        type: 'free',
      },
      {
        id: 'a11',
        time: '20:30',
        period: 'evening',
        title: 'Jantar na Trattoria Mario',
        description: 'Culinária toscana autêntica em ambiente familiar.',
        location: 'Trattoria Mario',
        duration: '2h',
        type: 'food',
        price: 'R$ 200',
      },
    ],
  },
  {
    id: 'd3',
    dayNumber: 3,
    date: '2025-06-17',
    title: 'Vinícolas do Chianti',
    intensity: 'medium',
    activities: [
      {
        id: 'a12',
        time: '09:00',
        period: 'morning',
        title: 'Saída para região do Chianti',
        description: 'Transfer privativo pela estrada panorâmica.',
        location: 'Florença → Chianti',
        duration: '1h',
        type: 'transport',
      },
      {
        id: 'a13',
        time: '10:30',
        period: 'morning',
        title: 'Visita à Vinícola Antinori',
        description: 'Tour completo com degustação de 5 vinhos premium.',
        location: 'Antinori nel Chianti Classico',
        duration: '2h30',
        type: 'experience',
        image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400',
        price: 'R$ 350',
        tips: ['Reserve com antecedência', 'Não dirija após a degustação'],
        miles: 2000,
      },
      {
        id: 'a14',
        time: '13:30',
        period: 'afternoon',
        title: 'Almoço na vinícola',
        description: 'Menu degustação harmonizado com vinhos locais.',
        location: 'Antinori nel Chianti Classico',
        duration: '2h',
        type: 'food',
        price: 'R$ 500',
      },
      {
        id: 'a15',
        time: '16:00',
        period: 'afternoon',
        title: 'Passeio por Greve in Chianti',
        description: 'Vilarejo típico toscano com praça medieval.',
        location: 'Greve in Chianti',
        duration: '2h',
        type: 'experience',
        image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=400',
      },
      {
        id: 'a16',
        time: '19:00',
        period: 'evening',
        title: 'Retorno a Florença',
        description: 'Transfer de volta ao hotel.',
        location: 'Chianti → Florença',
        duration: '1h',
        type: 'transport',
      },
    ],
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'm1',
    role: 'assistant',
    content: 'Olá! Sou a Voya, sua assistente de viagens. Vi que você está planejando uma viagem romântica para a Toscana. Posso ajudar a criar um roteiro inesquecível para vocês dois. Qual é o foco principal dessa viagem: gastronomia, arte, vinhos ou uma combinação de tudo?',
    timestamp: '2025-01-15T10:00:00',
    suggestions: ['Foco em gastronomia', 'Arte e história', 'Vinícolas e paisagens', 'Um pouco de tudo'],
  },
  {
    id: 'm2',
    role: 'user',
    content: 'Queremos um pouco de tudo, mas com foco especial em gastronomia e vinhos. Minha esposa adora arte também.',
    timestamp: '2025-01-15T10:01:00',
  },
  {
    id: 'm3',
    role: 'assistant',
    content: 'Perfeito! A Toscana é ideal para essa combinação. Já montei um roteiro de 7 dias que equilibra experiências gastronômicas autênticas, visitas às melhores vinícolas do Chianti e os tesouros artísticos de Florença. Inclui também uma passagem por Siena e San Gimignano. Você pode ver o roteiro completo no painel ao lado. Quer que eu ajuste algo específico?',
    timestamp: '2025-01-15T10:02:00',
    suggestions: ['Mais tempo em Florença', 'Adicionar aula de culinária', 'Incluir spa', 'Ver opções de hotéis'],
  },
];

export const experts: Expert[] = [
  {
    id: 'e1',
    name: 'Marina Costa',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    specialty: 'Europa Romântica',
    bio: 'Especialista em roteiros românticos pela Europa há 12 anos. Já ajudei mais de 500 casais a viverem suas viagens dos sonhos.',
    destinations: ['Itália', 'França', 'Grécia', 'Portugal'],
    rating: 4.9,
    reviews: 342,
    itineraries: 89,
    verified: true,
    featured: true,
  },
  {
    id: 'e2',
    name: 'Ricardo Yamamoto',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    specialty: 'Japão & Ásia',
    bio: 'Morei 5 anos no Japão e conheço cada canto desse país incrível. Do tradicional ao moderno, tenho o roteiro perfeito.',
    destinations: ['Japão', 'Coreia do Sul', 'Tailândia', 'Vietnã'],
    rating: 4.95,
    reviews: 287,
    itineraries: 67,
    verified: true,
    featured: true,
  },
  {
    id: 'e3',
    name: 'Carla Mendonça',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    specialty: 'Disney & Parques',
    bio: 'Viajei mais de 30 vezes para Orlando. Conheço todos os segredos dos parques e posso transformar sua viagem em magia.',
    destinations: ['Orlando', 'Los Angeles', 'Paris Disney', 'Tóquio Disney'],
    rating: 4.92,
    reviews: 521,
    itineraries: 134,
    verified: true,
  },
  {
    id: 'e4',
    name: 'Pedro Albuquerque',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    specialty: 'Viagens Econômicas',
    bio: 'Provo que viajar bem não precisa custar caro. Especialista em milhas, promoções e experiências incríveis com orçamento inteligente.',
    destinations: ['América do Sul', 'Sudeste Asiático', 'Europa Oriental'],
    rating: 4.88,
    reviews: 412,
    itineraries: 98,
    verified: true,
  },
  {
    id: 'e5',
    name: 'Ana Beatriz Lima',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200',
    specialty: 'Lua de Mel',
    bio: 'Wedding planner e travel expert. Crio experiências únicas para casais começarem sua vida juntos da melhor forma.',
    destinations: ['Maldivas', 'Bora Bora', 'Santorini', 'Seychelles'],
    rating: 4.97,
    reviews: 198,
    itineraries: 56,
    verified: true,
  },
  {
    id: 'e6',
    name: 'Fernando Duarte',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    specialty: 'Aventura & Natureza',
    bio: 'De trilhas na Patagônia a safaris na África. Se sua viagem envolve adrenalina e natureza, estou aqui para guiar.',
    destinations: ['Patagônia', 'Nova Zelândia', 'África do Sul', 'Islândia'],
    rating: 4.91,
    reviews: 267,
    itineraries: 72,
    verified: true,
  },
];

export const cards: Card[] = [
  {
    id: 'c1',
    name: 'Platinum',
    brand: 'amex',
    bank: 'American Express',
    lastDigits: '4521',
    color: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    benefits: [
      { id: 'b1', title: 'Sala VIP Priority Pass', description: 'Acesso ilimitado a mais de 1.300 salas VIP', category: 'lounge', active: true },
      { id: 'b2', title: 'Seguro Viagem Premium', description: 'Cobertura de até USD 1.000.000', category: 'insurance', active: true },
      { id: 'b3', title: 'Concierge 24h', description: 'Assistência pessoal a qualquer hora', category: 'concierge', active: true },
      { id: 'b4', title: 'Proteção de Bagagem', description: 'Até USD 3.000 em caso de extravio', category: 'insurance', active: true },
    ],
    milesProgram: 'Membership Rewards',
    milesBalance: 125000,
  },
  {
    id: 'c2',
    name: 'Ultravioleta',
    brand: 'mastercard',
    bank: 'Nubank',
    lastDigits: '8734',
    color: 'linear-gradient(135deg, #7c3aed 0%, #4c1d95 100%)',
    benefits: [
      { id: 'b5', title: 'Sala VIP LoungeKey', description: 'Até 6 acessos gratuitos por ano', category: 'lounge', active: true },
      { id: 'b6', title: 'Cashback em viagens', description: '2% de volta em compras internacionais', category: 'cashback', active: true },
      { id: 'b7', title: 'Seguro Viagem', description: 'Cobertura de até USD 500.000', category: 'insurance', active: true },
    ],
    milesProgram: 'Livelo',
    milesBalance: 45000,
  },
  {
    id: 'c3',
    name: 'Infinite',
    brand: 'visa',
    bank: 'Itaú',
    lastDigits: '2156',
    color: 'linear-gradient(135deg, #1e3a5f 0%, #0c1929 100%)',
    benefits: [
      { id: 'b8', title: 'Sala VIP Visa Airport', description: 'Até 8 acessos por ano', category: 'lounge', active: true },
      { id: 'b9', title: 'Upgrade de carro', description: 'Categoria superior na Hertz', category: 'priority', active: true },
      { id: 'b10', title: 'Concierge', description: 'Serviço de assistência pessoal', category: 'concierge', active: true },
    ],
    milesProgram: 'Iupp',
    milesBalance: 78000,
  },
];

export const milesPrograms: MilesProgram[] = [
  { id: 'mp1', name: 'LATAM Pass', logo: '/latam-logo.svg', balance: 85000, expiringMiles: 12000, expirationDate: '2025-03-31' },
  { id: 'mp2', name: 'Smiles', logo: '/smiles-logo.svg', balance: 42000 },
  { id: 'mp3', name: 'TudoAzul', logo: '/azul-logo.svg', balance: 28000, expiringMiles: 5000, expirationDate: '2025-02-28' },
  { id: 'mp4', name: 'Livelo', logo: '/livelo-logo.svg', balance: 45000 },
];

export const routeTemplates: RouteTemplate[] = [
  {
    id: 'r1',
    title: 'Disney Mágica em Família',
    description: 'Roteiro completo para 7 dias mágicos em Orlando com crianças. Inclui todos os parques, dicas de filas e restaurantes.',
    destination: 'Orlando, EUA',
    duration: '7 dias',
    coverImage: 'https://images.unsplash.com/photo-1597466599360-3b9775841aec?w=800',
    price: 'A partir de R$ 18.000',
    rating: 4.9,
    reviews: 234,
    tags: ['Família', 'Parques', 'Orlando'],
    expert: experts[2],
    featured: true,
  },
  {
    id: 'r2',
    title: 'Japão Primeira Vez',
    description: 'O guia definitivo para sua primeira viagem ao Japão. Tóquio, Kyoto e Monte Fuji em 14 dias inesquecíveis.',
    destination: 'Japão',
    duration: '14 dias',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
    price: 'A partir de R$ 22.000',
    rating: 4.95,
    reviews: 189,
    tags: ['Cultura', 'Gastronomia', 'Aventura'],
    expert: experts[1],
    featured: true,
  },
  {
    id: 'r3',
    title: 'Toscana Romântica',
    description: 'Vinícolas, gastronomia e arte na região mais romântica da Itália. Perfeito para casais.',
    destination: 'Toscana, Itália',
    duration: '7 dias',
    coverImage: 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800',
    price: 'A partir de R$ 25.000',
    rating: 4.92,
    reviews: 156,
    tags: ['Romântico', 'Gastronomia', 'Vinhos'],
    expert: experts[0],
  },
  {
    id: 'r4',
    title: 'Maldivas All-Inclusive',
    description: 'O paraíso na Terra para sua lua de mel ou férias especiais. Resorts 5 estrelas sobre as águas cristalinas.',
    destination: 'Ilhas Maldivas',
    duration: '5 dias',
    coverImage: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
    price: 'A partir de R$ 35.000',
    rating: 4.97,
    reviews: 98,
    tags: ['Lua de Mel', 'Praia', 'Luxo'],
    expert: experts[4],
  },
  {
    id: 'r5',
    title: 'Europa Econômica',
    description: 'Paris, Amsterdam e Bruxelas gastando pouco. Dicas de hospedagem, transporte e alimentação.',
    destination: 'Europa',
    duration: '12 dias',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    price: 'A partir de R$ 12.000',
    rating: 4.88,
    reviews: 312,
    tags: ['Econômico', 'Cultura', 'Europa'],
    expert: experts[3],
  },
  {
    id: 'r6',
    title: 'Patagônia Aventura',
    description: 'Trilhas épicas, glaciares e natureza selvagem no fim do mundo. Para aventureiros de verdade.',
    destination: 'Argentina/Chile',
    duration: '10 dias',
    coverImage: 'https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800',
    price: 'A partir de R$ 15.000',
    rating: 4.91,
    reviews: 145,
    tags: ['Aventura', 'Natureza', 'Trekking'],
    expert: experts[5],
  },
];

export const flights: Flight[] = [
  {
    id: 'f1',
    airline: 'LATAM',
    airlineLogo: '/latam-logo.svg',
    flightNumber: 'LA8084',
    departure: { airport: 'GRU', city: 'São Paulo', time: '22:30', date: '2025-06-15' },
    arrival: { airport: 'FCO', city: 'Roma', time: '14:45', date: '2025-06-16' },
    duration: '11h15m',
    stops: 0,
    price: 'R$ 4.850',
    miles: 85000,
    cabinClass: 'economy',
    benefits: ['Bagagem inclusa', '2x milhas no cartão Platinum'],
  },
  {
    id: 'f2',
    airline: 'Alitalia',
    airlineLogo: '/alitalia-logo.svg',
    flightNumber: 'AZ681',
    departure: { airport: 'GRU', city: 'São Paulo', time: '18:00', date: '2025-06-15' },
    arrival: { airport: 'FCO', city: 'Roma', time: '10:30', date: '2025-06-16' },
    duration: '11h30m',
    stops: 0,
    price: 'R$ 5.200',
    miles: 92000,
    cabinClass: 'economy',
    benefits: ['Bagagem inclusa'],
  },
  {
    id: 'f3',
    airline: 'TAP',
    airlineLogo: '/tap-logo.svg',
    flightNumber: 'TP92',
    departure: { airport: 'GRU', city: 'São Paulo', time: '21:15', date: '2025-06-15' },
    arrival: { airport: 'FCO', city: 'Roma', time: '17:30', date: '2025-06-16' },
    duration: '14h15m',
    stops: 1,
    price: 'R$ 3.980',
    miles: 72000,
    cabinClass: 'economy',
    benefits: ['Stopover em Lisboa disponível'],
  },
];

export const hotels: Hotel[] = [
  {
    id: 'h1',
    name: 'Four Seasons Hotel Firenze',
    location: 'Centro Histórico, Florença',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    rating: 4.9,
    reviews: 1243,
    price: 'R$ 8.400',
    pricePerNight: 'R$ 1.200/noite',
    amenities: ['Spa', 'Piscina', 'Restaurante', 'WiFi', 'Academia'],
    stars: 5,
    benefits: ['Late checkout', 'Upgrade de quarto', 'Crédito no spa'],
    miles: 15000,
  },
  {
    id: 'h2',
    name: 'Hotel Lungarno',
    location: 'Às margens do Arno, Florença',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
    rating: 4.8,
    reviews: 876,
    price: 'R$ 5.600',
    pricePerNight: 'R$ 800/noite',
    amenities: ['Restaurante', 'Bar', 'WiFi', 'Concierge'],
    stars: 5,
    benefits: ['Café da manhã incluso'],
    miles: 10000,
  },
  {
    id: 'h3',
    name: 'Portrait Firenze',
    location: 'Ponte Vecchio, Florença',
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
    rating: 4.95,
    reviews: 654,
    price: 'R$ 7.000',
    pricePerNight: 'R$ 1.000/noite',
    amenities: ['Suites', 'Terraço', 'Serviço de mordomo', 'WiFi'],
    stars: 5,
    benefits: ['Minibar incluso', 'Transfer aeroporto'],
    miles: 12000,
  },
];

export const experiences: Experience[] = [
  {
    id: 'ex1',
    title: 'Aula de Culinária Toscana',
    location: 'Florença, Itália',
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800',
    duration: '4 horas',
    price: 'R$ 450',
    rating: 4.9,
    reviews: 234,
    category: 'Gastronomia',
    description: 'Aprenda a fazer pasta fresca e tiramisu com um chef italiano autêntico.',
  },
  {
    id: 'ex2',
    title: 'Tour Privativo pela Galleria degli Uffizi',
    location: 'Florença, Itália',
    image: 'https://images.unsplash.com/photo-1504730030853-eff311f57d3c?w=800',
    duration: '3 horas',
    price: 'R$ 380',
    rating: 4.95,
    reviews: 189,
    category: 'Arte & Cultura',
    description: 'Explore as obras-primas do Renascimento com um historiador de arte.',
  },
  {
    id: 'ex3',
    title: 'Degustação nas Vinícolas do Chianti',
    location: 'Região do Chianti, Itália',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800',
    duration: '6 horas',
    price: 'R$ 520',
    rating: 4.92,
    reviews: 312,
    category: 'Vinho & Gastronomia',
    description: 'Visite 3 vinícolas premiadas e deguste os melhores vinhos da região.',
  },
  {
    id: 'ex4',
    title: 'Passeio de Balão sobre a Toscana',
    location: 'Siena, Itália',
    image: 'https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=800',
    duration: '2 horas',
    price: 'R$ 780',
    rating: 4.88,
    reviews: 87,
    category: 'Aventura',
    description: 'Veja o nascer do sol sobre os campos toscanos de uma perspectiva única.',
  },
];

export const plans: Plan[] = [
  {
    id: 'p1',
    name: 'Essencial',
    price: 'Grátis',
    period: '',
    description: 'Perfeito para começar a explorar a Voya',
    features: [
      'Criação de até 2 roteiros por mês',
      'Chat com IA básico',
      'Sugestões de destinos',
      'Compartilhamento de roteiros',
    ],
    cta: 'Começar Grátis',
  },
  {
    id: 'p2',
    name: 'Premium',
    price: 'R$ 29',
    period: '/mês',
    description: 'Para viajantes frequentes que querem o melhor',
    features: [
      'Roteiros ilimitados',
      'Chat com IA avançado',
      'Acesso a experts verificados',
      'Integração com milhas',
      'Alertas de promoções',
      'Exportação em PDF',
      'Sincronização com agenda',
    ],
    highlighted: true,
    cta: 'Assinar Premium',
  },
  {
    id: 'p3',
    name: 'Família',
    price: 'R$ 49',
    period: '/mês',
    description: 'Ideal para planejar viagens em grupo',
    features: [
      'Tudo do Premium',
      'Até 5 membros',
      'Roteiros colaborativos',
      'Concierge prioritário',
      'Descontos exclusivos em parceiros',
      'Suporte prioritário',
    ],
    cta: 'Assinar Família',
  },
];

export const travelStarters = [
  { id: 's1', label: 'Disney em família', icon: '🏰' },
  { id: 's2', label: 'Europa sem perrengue', icon: '🗼' },
  { id: 's3', label: 'Lua de mel', icon: '💑' },
  { id: 's4', label: 'Praia e descanso', icon: '🏖️' },
  { id: 's5', label: 'Japão pela primeira vez', icon: '🗾' },
  { id: 's6', label: 'Gastronomia e cultura', icon: '🍷' },
  { id: 's7', label: 'Econômico inteligente', icon: '💡' },
];
